name: Terraform Destroy

on:
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  WORK_DIR: environments/prod/

jobs:
  terraform-destroy:
    name: Terraform Destroy Production
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ${{ env.WORK_DIR }}
        run: terraform init

      - name: Terraform Destroy
        working-directory: ${{ env.WORK_DIR }}
        run: terraform destroy -auto-approve -var="rds_password=${{ secrets.RDS_PASSWORD }}" --var-file=terraform.tfvars
