apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: argocd
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: "5.47.2"
    helm:
      values: |
        deploymentMode: SingleBinary
        loki:
          commonConfig:
            replication_factor: 1
          storage:
            type: filesystem
          auth_enabled: false
        singleBinary:
          replicas: 1
          persistence:
            enabled: false
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 300m
              memory: 512Mi
        monitoring:
          selfMonitoring:
            enabled: false
            grafanaAgent:
              installOperator: false
          lokiCanary:
            enabled: false
        test:
          enabled: false
        gateway:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
