apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: argocd
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki-stack
    targetRevision: "2.10.2"
    helm:
      values: |
        loki:
          enabled: true
          persistence:
            enabled: false
        promtail:
          enabled: true
        grafana:
          enabled: false
        grafana.datasource:
          isDefault: false
        grafana.sidecar.datasources.defaultDatasourceEnabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: ""
      kind: ConfigMap
      name: loki-loki-stack
      namespace: monitoring
      jqPathExpressions:
        - .data["loki-stack-datasource.yaml"]
