apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: datadog
  namespace: argocd
spec:
  project: argocd
  source:
    repoURL: https://helm.datadoghq.com
    chart: datadog
    targetRevision: "3.69.0"
    helm:
      values: |
        datadog:
          apiKeyExistingSecret: datadog-secret
          apiKeyExistingSecretKey: api-key
          site: "datadoghq.com"
          apm:
            portEnabled: true
            port: 8126
          logs:
            enabled: true
            containerCollectAll: true
          otlp:
            receiver:
              protocols:
                grpc:
                  enabled: true
                  endpoint: "0.0.0.0:4317"
                http:
                  enabled: true
                  endpoint: "0.0.0.0:4318"
          tags:
            - "env:prod"
            - "project:togglemaster"
            - "cluster:togglemaster-eks"
          kubelet:
            tlsVerify: false
        clusterAgent:
          enabled: true
          metricsProvider:
            enabled: true
        agents:
          useHostNetwork: false
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 300m
            memory: 512Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: datadog
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
